name: tradelog_flutter
description: Tradely - Your trading journal
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  # Serverpod
  serverpod_flutter: 2.0.2

  # UI
  smooth_page_indicator: ^1.2.0+3
  cupertino_icons: ^1.0.5
  super_tooltip: ^2.0.8

  # NAVIGATION
  go_router: ^14.2.3
  sidebarx: ^0.17.1

  # TRADELY
  tradelog_client:
    git:
      url: https://lyte-manager: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@github.com/LYTE-studios/tradelog_client
      ref: main
  # LYTE STUDIOS
  lyte_studios_flutter_ui:
    git:
      url: https://lyte-manager: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@github.com/LYTE-studios/lyte_studios_flutter_ui
      ref: release/0.0.1

dev_dependencies:
  flutter_lints: '>=3.0.0 <5.0.0'
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/inter/Inter-Light.ttf
        - asset: assets/fonts/inter/Inter-Medium.ttf
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
        - asset: assets/fonts/inter/Inter-Thin.ttf
