name: tradelog_flutter
description: Tradely - Your trading journal
publish_to: 'none'
version: 1.0.0+16

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  # Serverpod
  serverpod_flutter: 2.1.3
  serverpod_auth_shared_flutter: 2.1.3
  serverpod_auth_email_flutter: 2.1.3
  serverpod_auth_google_flutter: 2.1.3

  # UI
  smooth_page_indicator: ^1.2.0+3
  cupertino_icons: ^1.0.5
  super_tooltip: ^2.0.8
  syncfusion_flutter_charts: ^22.2.9
  syncfusion_flutter_gauges: ^22.2.12
  syncfusion_flutter_datepicker: ^22.2.12
  flutter_svg_provider: ^1.0.7

  # NAVIGATION
  go_router: ^14.2.3

  # UTIL
  intl: ^0.19.0

  # TRADELY
  tradelog_client:
    git:
      url: https://github.com/LYTE-studios/tradelog_client
      ref: main
  lyte_studios_flutter_ui:
    git:
      url: https://github.com/LYTE-studios/lyte_studios_flutter_ui
      ref: main


  url_launcher: ^6.3.0
  flutter_quill: ^10.8.4
  flutter_quill_extensions: ^10.8.4
  file_picker: ^8.1.3
  image_picker: ^1.1.2
  flutter_heatmap_calendar: 1.0.5
  image: ^4.2.0


dependency_overrides:
  image_cropper: ^8.0.2
  intl: ^0.19.0  # Ensure all packages use intl ^0.19.0
  #tradelog_client:
  #  path: ../tradelog_client

dev_dependencies:
  flutter_lints: '>=3.0.0 <5.0.0'
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/images/emojis/

  fonts:
  - family: Phonk
    fonts:
      - asset: assets/fonts/phonk/Phonk-Contrast.otf
        weight: 900
#
  - family: Inter
    fonts:
      - asset: assets/fonts/inter/Inter-Black.ttf
      - asset: assets/fonts/inter/Inter-Bold.ttf
      - asset: assets/fonts/inter/Inter-ExtraBold.ttf
      - asset: assets/fonts/inter/Inter-ExtraLight.ttf
      - asset: assets/fonts/inter/Inter-Light.ttf
      - asset: assets/fonts/inter/Inter-Medium.ttf
      - asset: assets/fonts/inter/Inter-Regular.ttf
      - asset: assets/fonts/inter/Inter-SemiBold.ttf
      - asset: assets/fonts/inter/Inter-Thin.ttf

